### ISSUE TITLE
Failing assertion: a second round in the current lowering phase introduced these new nodes

### ISSUE THREAD

**Issue by smarr** [graalvm/graal#217]
When trying to confirm that https://github.com/graalvm/graal-core/issues/271 got fixed successfully, I stumbled into a new issue, using https://github.com/graalvm/graal/commit/eb130b8f66bcab141349b1709da6a63452ac2164

It looks roughly like this, full stacktrace in details:
```
HotSpotMethod<OptimizedCallTarget.callRoot(Object[])>}: a second round in the current lowering phase introduced these new nodes: [2420|==, 2421|<, 2422|Conditional, 2423|Conditional, 2424|==, 2425|<, 2426|Conditional, 2427|Conditional]
                Context obj org.graalvm.compiler.phases.common.LoweringPhase@743b8578
                Context obj org.graalvm.compiler.core.phases.HighTier@654e235f

```

<details>

```
Starting CD benchmark ... 
[thread:13] scope: TruffleCompilerThread-13
  [thread:13] scope: TruffleCompilerThread-13.Truffle
  Context: Truffle<Method_RedBlackTree>>#treeAt:insert:	@5b614145()>
    [thread:13] scope: TruffleCompilerThread-13.Truffle.TruffleGraal.GraalCompiler
    Context: StructuredGraph:4{Method RedBlackTree>>#treeAt:insert:	@5b614145, HotSpotMethod<OptimizedCallTarget.callRoot(Object[])>}
        [thread:13] scope: TruffleCompilerThread-13.Truffle.TruffleGraal.GraalCompiler.GraalCompilerRoot.GraalCompiler
        Context: StructuredGraph:4{Method RedBlackTree>>#treeAt:insert:	@5b614145, HotSpotMethod<OptimizedCallTarget.callRoot(Object[])>}
                [thread:13] scope: TruffleCompilerThread-13.Truffle.TruffleGraal.GraalCompiler.GraalCompilerRoot.GraalCompiler.FrontEnd.HighTier.LoweringPhase.InterceptException
                Exception occurred in scope: TruffleCompilerThread-13.Truffle.TruffleGraal.GraalCompiler.GraalCompilerRoot.GraalCompiler.FrontEnd.HighTier.LoweringPhase.InterceptException
                Context obj java.lang.AssertionError: StructuredGraph:4{Method RedBlackTree>>#treeAt:insert:	@5b614145, HotSpotMethod<OptimizedCallTarget.callRoot(Object[])>}: a second round in the current lowering phase introduced these new nodes: [2420|==, 2421|<, 2422|Conditional, 2423|Conditional, 2424|==, 2425|<, 2426|Conditional, 2427|Conditional]
                Context obj org.graalvm.compiler.phases.common.LoweringPhase@743b8578
                Context obj org.graalvm.compiler.core.phases.HighTier@654e235f
                Context obj StructuredGraph:4{Method RedBlackTree>>#treeAt:insert:	@5b614145, HotSpotMethod<OptimizedCallTarget.callRoot(Object[])>}
                Context obj jdk.vm.ci.hotspot.HotSpotCodeCacheProvider@5fa69b97
                Context obj Truffle<Method_RedBlackTree>>#treeAt:insert:	@5b614145()>
[truffle] opt fail         Method RedBlackTree>>#treeAt:insert:	@5b614145              |Reason java.lang.AssertionError: StructuredGraph:4{Method RedBlackTree>>#treeAt:insert:	@5b614145, HotSpotMethod<OptimizedCallTarget.callRoot(Object[])>}: a second round in the current lowering phase introduced these new nodes: [2420|==, 2421|<, 2422|Conditional, 2423|Conditional, 2424|==, 2425|<, 2426|Conditional, 2427|Conditional]
java.lang.AssertionError: StructuredGraph:4{Method RedBlackTree>>#treeAt:insert:	@5b614145, HotSpotMethod<OptimizedCallTarget.callRoot(Object[])>}: a second round in the current lowering phase introduced these new nodes: [2420|==, 2421|<, 2422|Conditional, 2423|Conditional, 2424|==, 2425|<, 2426|Conditional, 2427|Conditional]
	at org.graalvm.compiler.phases.common.LoweringPhase.checkPostLowering(LoweringPhase.java:235)
	at org.graalvm.compiler.phases.common.LoweringPhase.run(LoweringPhase.java:242)
	at org.graalvm.compiler.phases.common.LoweringPhase.run(LoweringPhase.java:86)
	at org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:187)
	at org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:139)
	at org.graalvm.compiler.phases.PhaseSuite.run(PhaseSuite.java:179)
	at org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:187)
	at org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:139)
	at org.graalvm.compiler.core.GraalCompiler.emitFrontEnd(GraalCompiler.java:231)
	at org.graalvm.compiler.core.GraalCompiler.compile(GraalCompiler.java:174)
	at org.graalvm.compiler.core.GraalCompiler.compileGraph(GraalCompiler.java:160)
	at org.graalvm.compiler.truffle.TruffleCompiler.compileMethodHelper(TruffleCompiler.java:224)
	at org.graalvm.compiler.truffle.TruffleCompiler.compileMethod(TruffleCompiler.java:177)
	at org.graalvm.compiler.truffle.GraalTruffleRuntime.doCompile0(GraalTruffleRuntime.java:529)
	at org.graalvm.compiler.truffle.GraalTruffleRuntime.doCompile(GraalTruffleRuntime.java:515)
	at org.graalvm.compiler.truffle.GraalTruffleRuntime$1.run(GraalTruffleRuntime.java:560)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
	at org.graalvm.compiler.core.CompilerThread.run(CompilerThread.java:51)
```

</details>

To reproduce the problem, you can use the following steps:

```bash
git clone https://github.com/smarr/SOMns
cd SOMns
ant compile

export JVMCI_BIN=$YOUR_PATH_TO_YOUR_GRAAL_JVMCI_BINARY
export GRAAL_FLAGS=$ANY_GRAAL_FLAGS_PERHAPS
./som -t1  core-lib/Benchmarks/Harness.som CD  130 0 100
```

To determine the plain `java` command-line, use `-vv`:
```bash
./som -t1 -vv core-lib/Benchmarks/Harness.som CD  130 0 100
```

**Comment by tkrodriguez** [comment]
hmm.  This looks a bit like it's related to the NormalizeCompare changes since that looks like the normalize compare lowering.  I'll take a look.

**Comment by tkrodriguez** [comment]
This is fixed in https://github.com/graalvm/graal/commit/f946b50f3186eb9bad0301f37335788e6eba0767

**Comment by smarr** [comment]
Can't confirm at the moment, seems to require a Truffle update.

**Comment by smarr** [comment]
Seems fixed, thanks!
