### ISSUE TITLE
Assertion failure in LoopFragmentInside.insertWithinAfter

### ISSUE THREAD

**Issue by smarr** [graalvm/graal#252]
After updating Graal/Truffle to https://github.com/graalvm/graal/commit/b8870391f574bb4d1663423ebb7f56b1ec27fbc0, I am seeing the following assertion failing:

```
java.lang.AssertionError
	at org.graalvm.compiler.loop.LoopFragmentInside.insertWithinAfter(LoopFragmentInside.java:195)
	at org.graalvm.compiler.loop.LoopFragmentInside.insertWithinAfter(LoopFragmentInside.java:153)
	at org.graalvm.compiler.loop.phases.LoopTransformations.partialUnroll(LoopTransformations.java:154)
	at org.graalvm.compiler.loop.phases.LoopPartialUnrollPhase.run(LoopPartialUnrollPhase.java:67)
	at org.graalvm.compiler.loop.phases.LoopPartialUnrollPhase.run(LoopPartialUnrollPhase.java:34)
	at org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:195)
	at org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:137)
	at org.graalvm.compiler.phases.PhaseSuite.run(PhaseSuite.java:203)
	at org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:195)
	at org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:137)
	at org.graalvm.compiler.core.GraalCompiler.emitFrontEnd(GraalCompiler.java:234)
	at org.graalvm.compiler.core.GraalCompiler.compile(GraalCompiler.java:172)
	at org.graalvm.compiler.core.GraalCompiler.compileGraph(GraalCompiler.java:158)
	at org.graalvm.compiler.truffle.TruffleCompiler.compileMethodHelper(TruffleCompiler.java:232)
	at org.graalvm.compiler.truffle.TruffleCompiler.compileMethod(TruffleCompiler.java:181)
```

To reproduce the problem, you can use the following steps:

```bash
git clone -b dev https://github.com/smarr/SOMns
cd SOMns
ant compile

export JVMCI_BIN=$YOUR_PATH_TO_YOUR_GRAAL_JVMCI_BINARY
export GRAAL_FLAGS=$ANY_GRAAL_FLAGS_PERHAPS
./som -t1  core-lib/Benchmarks/AsyncHarness.ns Savina.UnbalancedCobwebbedTree 100 25  100000:10:500:100
```

The assertion triggers mostly deterministic, but not in 100% of the runs.

To determine the plain `java` command-line, use `-vv`:
```bash
./som -t1 -vv core-lib/Benchmarks/AsyncHarness.ns Savina.UnbalancedCobwebbedTree 100 25  100000:10:500:100
```

**Comment by tkrodriguez** [comment]
Some recent changes to NodeBitMap were using int to build a mask instead of long so it was clearing some bits it shouldn't.  A fix is on it's way.  You can work around it with -Dgraal.PartialUnroll=false

**Comment by smarr** [comment]
@tkrodriguez looks good. I updated Graal to https://github.com/graalvm/graal/commit/98115995e12e76be0279cf0173c3df68726b7a01 i.e. past https://github.com/graalvm/graal/commit/fc8f331d9f60b446d3bb7231ed0f44e65c532e95 and the assertion doesn't trigger anymore.

Thanks!
