### ISSUE TITLE
Regression: com/sun/net/httpserver/Test7a.java fails with graal-0.27

### ISSUE THREAD

**Issue by christhalinger** [graalvm/graal#255]
We are currently on graal-0.22 and want to upgrade to 0.27.  Running all `hotspot` and `jdk` regression tests shows two new failures. Here is one of them:

```
--------------------------------------------------
TEST: com/sun/net/httpserver/Test7a.java
TEST JDK: /data/jenkins/workspace/jdk8-centos7-release/usr/lib/jvm/java-1.8.0-twitter

ACTION: build -- Passed. Build successful
REASON: Named class compiled on demand
TIME:   0.067 seconds
messages:
command: build Test7a
reason: Named class compiled on demand
Test directory:
  compile: Test7a
elapsed time (seconds): 0.067

ACTION: compile -- Passed. Compilation successful
REASON: .class file out of date or does not exist
TIME:   0.067 seconds
messages:
command: compile -XDignore.symbol.file=true /data/jenkins/workspace/jdk8-centos7-release/jdk/test/com/sun/net/httpserver/Test7a.java
reason: .class file out of date or does not exist
Mode: agentvm
Agent id: 2
elapsed time (seconds): 0.067
configuration:
Boot Layer (javac runtime environment)
  class path: /data/jenkins/workspace/jdk8-centos7-release/usr/lib/jvm/java-1.8.0-twitter/lib/tools.jar
              /data/jenkins/workspace/jdk8-centos7-release/jtreg/lib/javatest.jar
              /data/jenkins/workspace/jdk8-centos7-release/jtreg/lib/jtreg.jar

javac compilation environment
  source path: /data/jenkins/workspace/jdk8-centos7-release/jdk/test/com/sun/net/httpserver
  class path:  /data/jenkins/workspace/jdk8-centos7-release/jdk/test/com/sun/net/httpserver
               /data/jenkins/workspace/jdk8-centos7-release/jdk/testoutput/jdk_core/JTwork/classes/2/com/sun/net/httpserver
               /data/jenkins/workspace/jdk8-centos7-release/usr/lib/jvm/java-1.8.0-twitter/lib/tools.jar

rerun:
HOME=/var/lib/jenkins \
LANG=en_US.UTF-8 \
PATH=/bin:/usr/bin \
    /data/jenkins/workspace/jdk8-centos7-release/usr/lib/jvm/java-1.8.0-twitter/bin/javac \
        -J-ea \
        -J-esa \
        -J-XX:+UnlockExperimentalVMOptions \
        -J-XX:+EnableJVMCI \
        -J-XX:+UseJVMCICompiler \
        -J-XX:+UseConcMarkSweepGC \
        -J-Xmx512m \
        -J-XX:+UnlockExperimentalVMOptions \
        -J-XX:+EnableJVMCI \
        -J-XX:+UseJVMCICompiler \
        -J-XX:+UseConcMarkSweepGC \
        -J-Dtest.class.path.prefix=/data/jenkins/workspace/jdk8-centos7-release/jdk/testoutput/jdk_core/JTwork/classes/2/com/sun/net/httpserver:/data/jenkins/workspace/jdk8-centos7-release/jdk/test/com/sun/net/httpserver \
        -J-Dtest.src=/data/jenkins/workspace/jdk8-centos7-release/jdk/test/com/sun/net/httpserver \
        -J-Dtest.src.path=/data/jenkins/workspace/jdk8-centos7-release/jdk/test/com/sun/net/httpserver \
        -J-Dtest.classes=/data/jenkins/workspace/jdk8-centos7-release/jdk/testoutput/jdk_core/JTwork/classes/2/com/sun/net/httpserver \
        -J-Dtest.class.path=/data/jenkins/workspace/jdk8-centos7-release/jdk/testoutput/jdk_core/JTwork/classes/2/com/sun/net/httpserver \
        -J-Dtest.vm.opts='-ea -esa -XX:+UnlockExperimentalVMOptions -XX:+EnableJVMCI -XX:+UseJVMCICompiler -XX:+UseConcMarkSweepGC -Xmx512m' \
        -J-Dtest.tool.vm.opts='-J-ea -J-esa -J-XX:+UnlockExperimentalVMOptions -J-XX:+EnableJVMCI -J-XX:+UseJVMCICompiler -J-XX:+UseConcMarkSweepGC -J-Xmx512m' \
        -J-Dtest.compiler.opts= \
        -J-Dtest.java.opts='-XX:+UnlockExperimentalVMOptions -XX:+EnableJVMCI -XX:+UseJVMCICompiler -XX:+UseConcMarkSweepGC' \
        -J-Dtest.jdk=/data/jenkins/workspace/jdk8-centos7-release/usr/lib/jvm/java-1.8.0-twitter \
        -J-Dcompile.jdk=/data/jenkins/workspace/jdk8-centos7-release/usr/lib/jvm/java-1.8.0-twitter \
        -J-Dtest.timeout.factor=4.0 \
        -d /data/jenkins/workspace/jdk8-centos7-release/jdk/testoutput/jdk_core/JTwork/classes/2/com/sun/net/httpserver \
        -sourcepath /data/jenkins/workspace/jdk8-centos7-release/jdk/test/com/sun/net/httpserver \
        -classpath /data/jenkins/workspace/jdk8-centos7-release/jdk/test/com/sun/net/httpserver:/data/jenkins/workspace/jdk8-centos7-release/jdk/testoutput/jdk_core/JTwork/classes/2/com/sun/net/httpserver:/data/jenkins/workspace/jdk8-centos7-release/usr/lib/jvm/java-1.8.0-twitter/lib/tools.jar \
        -XDignore.symbol.file=true /data/jenkins/workspace/jdk8-centos7-release/jdk/test/com/sun/net/httpserver/Test7a.java

ACTION: main -- Failed. Unexpected exit from test [exit code: 255]
REASON: User specified action: run main/othervm Test7a 
TIME:   3.018 seconds
messages:
command: main Test7a
reason: User specified action: run main/othervm Test7a 
Mode: othervm [/othervm specified]
elapsed time (seconds): 3.018
configuration:
STDOUT:
Test7a: Dumping debug output in /data/jenkins/workspace/jdk8-centos7-release/jdk/testoutput/jdk_core/JTwork/scratch/2/dumps/1505348121154
Thread[JVMCI CompilerThread7,9,system]: Compilation of Test7a$Handler.handle(HttpExchange) failed: java.lang.NullPointerException
	at org.graalvm.compiler.hotspot.replacements.HubGetClassNode.canonical(HubGetClassNode.java:74)
	at org.graalvm.compiler.nodes.SimplifyingGraphDecoder.handleFloatingNodeBeforeAdd(SimplifyingGraphDecoder.java:311)
	at org.graalvm.compiler.nodes.GraphDecoder.ensureNodeCreated(GraphDecoder.java:1094)
	at org.graalvm.compiler.nodes.GraphDecoder.handlePhiFunctions(GraphDecoder.java:953)
	at org.graalvm.compiler.nodes.GraphDecoder.processNextNode(GraphDecoder.java:567)
	at org.graalvm.compiler.nodes.GraphDecoder.decode(GraphDecoder.java:403)
	at org.graalvm.compiler.nodes.GraphDecoder.decode(GraphDecoder.java:362)
	at org.graalvm.compiler.hotspot.meta.HotSpotSuitesProvider$1.run(HotSpotSuitesProvider.java:139)
	at org.graalvm.compiler.hotspot.meta.HotSpotSuitesProvider$1.run(HotSpotSuitesProvider.java:131)
	at org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:195)
	at org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:137)
	at org.graalvm.compiler.phases.PhaseSuite.run(PhaseSuite.java:203)
	at org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:195)
	at org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:137)
	at org.graalvm.compiler.phases.common.inlining.info.elem.InlineableGraph.parseBytecodes(InlineableGraph.java:204)
	at org.graalvm.compiler.phases.common.inlining.info.elem.InlineableGraph.getOriginalGraph(InlineableGraph.java:86)
	at org.graalvm.compiler.phases.common.inlining.info.elem.InlineableGraph.<init>(InlineableGraph.java:70)
	at org.graalvm.compiler.phases.common.inlining.info.elem.Inlineable.getInlineableElement(Inlineable.java:36)
	at org.graalvm.compiler.phases.common.inlining.info.AbstractInlineInfo.populateInlinableElements(AbstractInlineInfo.java:67)
	at org.graalvm.compiler.phases.common.inlining.walker.InliningData.processNextInvoke(InliningData.java:494)
	at org.graalvm.compiler.phases.common.inlining.walker.InliningData.moveForward(InliningData.java:722)
	at org.graalvm.compiler.phases.common.inlining.InliningPhase.run(InliningPhase.java:108)
	at org.graalvm.compiler.phases.common.inlining.InliningPhase.run(InliningPhase.java:40)
	at org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:195)
	at org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:137)
	at org.graalvm.compiler.phases.PhaseSuite.run(PhaseSuite.java:203)
	at org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:195)
	at org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:137)
	at org.graalvm.compiler.core.GraalCompiler.emitFrontEnd(GraalCompiler.java:229)
	at org.graalvm.compiler.core.GraalCompiler.compile(GraalCompiler.java:172)
	at org.graalvm.compiler.core.GraalCompiler.compileGraph(GraalCompiler.java:158)
	at org.graalvm.compiler.hotspot.HotSpotGraalCompiler.compile(HotSpotGraalCompiler.java:180)
	at org.graalvm.compiler.hotspot.CompilationTask$HotSpotCompilationWrapper.performCompilation(CompilationTask.java:169)
	at org.graalvm.compiler.hotspot.CompilationTask$HotSpotCompilationWrapper.performCompilation(CompilationTask.java:94)
	at org.graalvm.compiler.core.CompilationWrapper.run(CompilationWrapper.java:185)
	at org.graalvm.compiler.hotspot.CompilationTask.runCompilation(CompilationTask.java:317)
	at org.graalvm.compiler.hotspot.HotSpotGraalCompiler.compileMethod(HotSpotGraalCompiler.java:142)
	at org.graalvm.compiler.hotspot.HotSpotGraalCompiler.compileMethod(HotSpotGraalCompiler.java:108)
	at jdk.vm.ci.hotspot.HotSpotJVMCIRuntime.compileMethod(HotSpotJVMCIRuntime.java:432)
To disable compilation failure notifications, set CompilationFailureAction to Silent (e.g., -Dgraal.CompilationFailureAction=Silent).
To print a message for a compilation failure without retrying the compilation, set CompilationFailureAction to Print (e.g., -Dgraal.CompilationFailureAction=Print).
Retrying compilation of Test7a$Handler.handle(HttpExchange)

Dumping debug output to /data/jenkins/workspace/jdk8-centos7-release/jdk/testoutput/jdk_core/JTwork/scratch/2/dumps/1505348121154/graal_diagnostics_8013/Test7a$Handler.handle(HttpExchange)/HotSpotOSRCompilation-1349[Test7a$Handler.handle(HttpExchange)].bgv
[thread:14] scope: JVMCI CompilerThread7
    [thread:14] scope: JVMCI CompilerThread7.Compiling.GraalCompiler
    Context: StructuredGraph:2360{HotSpotMethod<Test7a$Handler.handle(HttpExchange)>}
            [thread:14] scope: JVMCI CompilerThread7.Compiling.GraalCompiler.FrontEnd.HighTier.InliningPhase.InlineGraph
            Context: StructuredGraph:5034{HotSpotMethod<SocketChannelImpl.toString()>}
                  [thread:14] scope: JVMCI CompilerThread7.Compiling.GraalCompiler.FrontEnd.HighTier.InliningPhase.InlineGraph.PhaseSuite.HotSpotSuitesProvider_.GraphDecoder
                  Context: StructuredGraph:5130{HotSpotMethod<SocketChannelImpl.toString()>}
                  Exception raised in scope JVMCI CompilerThread7.Compiling.GraalCompiler.FrontEnd.HighTier.InliningPhase.InlineGraph.PhaseSuite.HotSpotSuitesProvider_.GraphDecoder: java.lang.NullPointerException
                  	at org.graalvm.compiler.hotspot.replacements.HubGetClassNode.canonical(HubGetClassNode.java:74)
                  	at org.graalvm.compiler.nodes.SimplifyingGraphDecoder.handleFloatingNodeBeforeAdd(SimplifyingGraphDecoder.java:311)
                  	at org.graalvm.compiler.nodes.GraphDecoder.ensureNodeCreated(GraphDecoder.java:1094)
                  	at org.graalvm.compiler.nodes.GraphDecoder.handlePhiFunctions(GraphDecoder.java:953)
                  	at org.graalvm.compiler.nodes.GraphDecoder.processNextNode(GraphDecoder.java:567)
                  	at org.graalvm.compiler.nodes.GraphDecoder.decode(GraphDecoder.java:403)
                  	at org.graalvm.compiler.nodes.GraphDecoder.decode(GraphDecoder.java:362)
                  	at org.graalvm.compiler.hotspot.meta.HotSpotSuitesProvider$1.run(HotSpotSuitesProvider.java:139)
                  	at org.graalvm.compiler.hotspot.meta.HotSpotSuitesProvider$1.run(HotSpotSuitesProvider.java:131)
                  	at org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:195)
                  	at org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:137)
                  	at org.graalvm.compiler.phases.PhaseSuite.run(PhaseSuite.java:203)
                  	at org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:195)
                  	at org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:137)
                  	at org.graalvm.compiler.phases.common.inlining.info.elem.InlineableGraph.parseBytecodes(InlineableGraph.java:204)
                  	at org.graalvm.compiler.phases.common.inlining.info.elem.InlineableGraph.getOriginalGraph(InlineableGraph.java:86)
                  	at org.graalvm.compiler.phases.common.inlining.info.elem.InlineableGraph.<init>(InlineableGraph.java:70)
                  	at org.graalvm.compiler.phases.common.inlining.info.elem.Inlineable.getInlineableElement(Inlineable.java:36)
                  	at org.graalvm.compiler.phases.common.inlining.info.AbstractInlineInfo.populateInlinableElements(AbstractInlineInfo.java:67)
                  	at org.graalvm.compiler.phases.common.inlining.walker.InliningData.processNextInvoke(InliningData.java:494)
                  	at org.graalvm.compiler.phases.common.inlining.walker.InliningData.moveForward(InliningData.java:722)
                  	at org.graalvm.compiler.phases.common.inlining.InliningPhase.run(InliningPhase.java:108)
                  	at org.graalvm.compiler.phases.common.inlining.InliningPhase.run(InliningPhase.java:40)
                  	at org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:195)
                  	at org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:137)
                  	at org.graalvm.compiler.phases.PhaseSuite.run(PhaseSuite.java:203)
                  	at org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:195)
                  	at org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:137)
                  	at org.graalvm.compiler.core.GraalCompiler.emitFrontEnd(GraalCompiler.java:229)
                  	at org.graalvm.compiler.core.GraalCompiler.compile(GraalCompiler.java:172)
                  	at org.graalvm.compiler.core.GraalCompiler.compileGraph(GraalCompiler.java:158)
                  	at org.graalvm.compiler.hotspot.HotSpotGraalCompiler.compile(HotSpotGraalCompiler.java:180)
                  	at org.graalvm.compiler.hotspot.CompilationTask$HotSpotCompilationWrapper.performCompilation(CompilationTask.java:169)
                  	at org.graalvm.compiler.hotspot.CompilationTask$HotSpotCompilationWrapper.performCompilation(CompilationTask.java:94)
                  	at org.graalvm.compiler.core.CompilationWrapper.run(CompilationWrapper.java:285)
                  	at org.graalvm.compiler.hotspot.CompilationTask.runCompilation(CompilationTask.java:317)
                  	at org.graalvm.compiler.hotspot.HotSpotGraalCompiler.compileMethod(HotSpotGraalCompiler.java:142)
                  	at org.graalvm.compiler.hotspot.HotSpotGraalCompiler.compileMethod(HotSpotGraalCompiler.java:108)
                  	at jdk.vm.ci.hotspot.HotSpotJVMCIRuntime.compileMethod(HotSpotJVMCIRuntime.java:432)
                  
Dumping debug output to /data/jenkins/workspace/jdk8-centos7-release/jdk/testoutput/jdk_core/JTwork/scratch/2/dumps/1505348121154/graal_diagnostics_8013/Test7a$Handler.handle(HttpExchange)/HotSpotOSRCompilation-1349[Test7a$Handler.handle(HttpExchange)].cfg
Exiting VM after retry compilation of Test7a$Handler.handle(HttpExchange)
Graal diagnostic output saved in /data/jenkins/workspace/jdk8-centos7-release/jdk/testoutput/jdk_core/JTwork/scratch/2/dumps/1505348121154/graal_diagnostics_8013.zip
STDERR:
rerun:
HOME=/var/lib/jenkins \
LANG=en_US.UTF-8 \
PATH=/bin:/usr/bin \
CLASSPATH=/data/jenkins/workspace/jdk8-centos7-release/jdk/testoutput/jdk_core/JTwork/classes/2/com/sun/net/httpserver:/data/jenkins/workspace/jdk8-centos7-release/jdk/test/com/sun/net/httpserver:/data/jenkins/workspace/jdk8-centos7-release/usr/lib/jvm/java-1.8.0-twitter/lib/tools.jar:/data/jenkins/workspace/jdk8-centos7-release/jtreg/lib/javatest.jar:/data/jenkins/workspace/jdk8-centos7-release/jtreg/lib/jtreg.jar \
    /data/jenkins/workspace/jdk8-centos7-release/usr/lib/jvm/java-1.8.0-twitter/bin/java \
        -Dtest.class.path.prefix=/data/jenkins/workspace/jdk8-centos7-release/jdk/testoutput/jdk_core/JTwork/classes/2/com/sun/net/httpserver:/data/jenkins/workspace/jdk8-centos7-release/jdk/test/com/sun/net/httpserver \
        -Dtest.src=/data/jenkins/workspace/jdk8-centos7-release/jdk/test/com/sun/net/httpserver \
        -Dtest.src.path=/data/jenkins/workspace/jdk8-centos7-release/jdk/test/com/sun/net/httpserver \
        -Dtest.classes=/data/jenkins/workspace/jdk8-centos7-release/jdk/testoutput/jdk_core/JTwork/classes/2/com/sun/net/httpserver \
        -Dtest.class.path=/data/jenkins/workspace/jdk8-centos7-release/jdk/testoutput/jdk_core/JTwork/classes/2/com/sun/net/httpserver \
        -Dtest.vm.opts='-ea -esa -XX:+UnlockExperimentalVMOptions -XX:+EnableJVMCI -XX:+UseJVMCICompiler -XX:+UseConcMarkSweepGC -Xmx512m' \
        -Dtest.tool.vm.opts='-J-ea -J-esa -J-XX:+UnlockExperimentalVMOptions -J-XX:+EnableJVMCI -J-XX:+UseJVMCICompiler -J-XX:+UseConcMarkSweepGC -J-Xmx512m' \
        -Dtest.compiler.opts= \
        -Dtest.java.opts='-XX:+UnlockExperimentalVMOptions -XX:+EnableJVMCI -XX:+UseJVMCICompiler -XX:+UseConcMarkSweepGC' \
        -Dtest.jdk=/data/jenkins/workspace/jdk8-centos7-release/usr/lib/jvm/java-1.8.0-twitter \
        -Dcompile.jdk=/data/jenkins/workspace/jdk8-centos7-release/usr/lib/jvm/java-1.8.0-twitter \
        -Dtest.timeout.factor=4.0 \
        -ea \
        -esa \
        -XX:+UnlockExperimentalVMOptions \
        -XX:+EnableJVMCI \
        -XX:+UseJVMCICompiler \
        -XX:+UseConcMarkSweepGC \
        -Xmx512m \
        -XX:+UnlockExperimentalVMOptions \
        -XX:+EnableJVMCI \
        -XX:+UseJVMCICompiler \
        -XX:+UseConcMarkSweepGC \
        com.sun.javatest.regtest.agent.MainWrapper /data/jenkins/workspace/jdk8-centos7-release/jdk/testoutput/jdk_core/JTwork/com/sun/net/httpserver/Test7a.d/main.0.jta

TEST RESULT: Failed. Unexpected exit from test [exit code: 255]
--------------------------------------------------
```

**Comment by dougxc** [comment]
@christianwimmer , looks like the `hub` input to a `HubGetClassNode` is null during graph decoding. How can this happen?

**Comment by tkrodriguez** [comment]
Could it be that the node isn't in a graph yet, so the NPE is here `GraalOptions.ImmutableCode.getValue(graph().getOptions())`?  Looking at the code I think that's the most likely case.  Seems like this is just a side effect of making our options be contextual.  I think any use of options inside canonical is questionable for this reason.  It seems like most of the option checks use CanonicalizerTool.getOptions but a few were missed.

**Comment by dougxc** [comment]
You're right - the source of the NPE is not what I thought it was.

**Comment by tkrodriguez** [comment]
resolved by getOptions fix.
