### ISSUE TITLE
javax/management/query/CustomQueryTest.java fails with graal-0.28

### ISSUE THREAD

**Issue by christhalinger** [graalvm/graal#258]
I've updated our JDK to 0.28 and now we are getting this exception which worries me a bit:

```
Uncaught exception at /builddir/build/BUILD/hotspot/src/share/vm/jvmci/jvmciCompiler.cpp:125
java.util.ServiceConfigurationError: org.graalvm.compiler.options.OptionDescriptors: Provider org.graalvm.compiler.hotspot.stubs.StubOptions_OptionDescriptors could not be instantiated
	at java.util.ServiceLoader.fail(ServiceLoader.java:232)
	at java.util.ServiceLoader.access$100(ServiceLoader.java:185)
	at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:384)
	at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:404)
	at java.util.ServiceLoader$1.next(ServiceLoader.java:480)
	at org.graalvm.compiler.options.OptionKey$Lazy.<clinit>(OptionKey.java:87)
	at org.graalvm.compiler.options.OptionKey.checkDescriptorExists(OptionKey.java:62)
	at org.graalvm.compiler.options.OptionKey.getValue(OptionKey.java:137)
	at org.graalvm.compiler.hotspot.HotSpotGraalCompilerFactory.initializeGraalCompilePolicyFields(HotSpotGraalCompilerFactory.java:80)
	at org.graalvm.compiler.hotspot.HotSpotGraalCompilerFactory.onSelection(HotSpotGraalCompilerFactory.java:70)
	at jdk.vm.ci.hotspot.HotSpotJVMCICompilerConfig.getCompilerFactory(HotSpotJVMCICompilerConfig.java:127)
	at jdk.vm.ci.hotspot.HotSpotJVMCIRuntime.<init>(HotSpotJVMCIRuntime.java:289)
	at jdk.vm.ci.hotspot.HotSpotJVMCIRuntime.<init>(HotSpotJVMCIRuntime.java:65)
	at jdk.vm.ci.hotspot.HotSpotJVMCIRuntime$DelayedInit.<clinit>(HotSpotJVMCIRuntime.java:73)
	at jdk.vm.ci.hotspot.HotSpotJVMCIRuntime.runtime(HotSpotJVMCIRuntime.java:83)
	at jdk.vm.ci.runtime.JVMCI.initializeRuntime(Native Method)
	at jdk.vm.ci.runtime.JVMCI.<clinit>(JVMCI.java:58)
Caused by: java.util.ConcurrentModificationException
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1437)
	at java.util.HashMap$KeyIterator.next(HashMap.java:1461)
	at DcmdMBeanPermissionsTest$CustomSecurityManager.checkPermission(DcmdMBeanPermissionsTest.java:85)
	at java.lang.reflect.AccessibleObject.setAccessible(AccessibleObject.java:128)
	at java.lang.Class$1.run(Class.java:420)
	at java.lang.Class$1.run(Class.java:418)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.lang.Class.newInstance(Class.java:417)
	at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:380)
	at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:404)
	at java.util.ServiceLoader$1.next(ServiceLoader.java:480)
	at org.graalvm.compiler.options.OptionKey$Lazy.<clinit>(OptionKey.java:87)
	at org.graalvm.compiler.options.OptionKey.checkDescriptorExists(OptionKey.java:62)
	at org.graalvm.compiler.options.OptionKey.getValue(OptionKey.java:137)
	at org.graalvm.compiler.hotspot.HotSpotGraalCompilerFactory.initializeGraalCompilePolicyFields(HotSpotGraalCompilerFactory.java:80)
	at org.graalvm.compiler.hotspot.HotSpotGraalCompilerFactory.onSelection(HotSpotGraalCompilerFactory.java:70)
	at jdk.vm.ci.hotspot.HotSpotJVMCICompilerConfig.getCompilerFactory(HotSpotJVMCICompilerConfig.java:127)
	at jdk.vm.ci.hotspot.HotSpotJVMCIRuntime.<init>(HotSpotJVMCIRuntime.java:289)
	at jdk.vm.ci.hotspot.HotSpotJVMCIRuntime.<init>(HotSpotJVMCIRuntime.java:65)
	at jdk.vm.ci.hotspot.HotSpotJVMCIRuntime$DelayedInit.<clinit>(HotSpotJVMCIRuntime.java:73)
	at jdk.vm.ci.hotspot.HotSpotJVMCIRuntime.runtime(HotSpotJVMCIRuntime.java:83)
	at jdk.vm.ci.runtime.JVMCI.initializeRuntime(Native Method)
	at jdk.vm.ci.runtime.JVMCI.<clinit>(JVMCI.java:58)
```

**Comment by tkrodriguez** [comment]
I think the security manager in that test is poorly written.  It's setting a global property, the security manager, and then modifying it without synchronization which could certainly lead to a failure of this sort.  Running Graal with a security manager is a tricky issue in the first place but I suspect there's literally nothing Graal could do to make this security manager work properly in this context.

**Comment by dougxc** [comment]
So we should close this as a test bug @tkrodriguez ?

**Comment by tkrodriguez** [comment]
The reported issue is a test bug I think but I suspect that if we fix the test then Graal itself will stop working because we don't have the required permissions.  We should consider modifying the default jre/lib/java.policy to include some rules to let graal run in the presence of a security manager.  Looking at it now, I think something like this line would work for the normal case of Graal as the JVMCI compiler.

grant codeBase "file:${{jvmci.class.path.append}}/*" {
        permission java.security.AllPermission;
};

I suspect it wouldn't be sufficient for something like truffle or other direct uses of Graal API by user code.  I'll try it out for this program and we can include the new permission in our build scripts for JVMCI.

**Comment by tkrodriguez** [comment]
So I looked at this a bit more and basically this test is generally incompatible with running the compiler in Java.  It creates it's own SecurityManager which ignores the default policy so there's no way we can run a JVMCI compiler while it's installed.  So the JVMCI compiles will all fail though it doesn't actually cause problems with the test.  So synchronizing the security manager will let it work as well as it ever can.  But the test itself always fails for me because it doesn't allow reading of javatest.jar so I don't know how this works normally.

Exception in thread "main" java.lang.SecurityException: ("java.io.FilePermission" "/Users/tkrodrig/Downloads/jtreg/lib/javatest.jar" "read")
	at DcmdMBeanPermissionsTest$CustomSecurityManager.checkPermission(DcmdMBeanPermissionsTest.java:90)

Anyway, I'd say this is a test bug.

**Comment by christhalinger** [comment]
The odd part is that it started to fail with 0.27 but differently as you can see in #256.  And the test is around for a long time:

```
$ hg log test/javax/management/query/CustomQueryTest.java 
changeset:   2362:00cd9dc3c2b5
parent:      2360:cf44386c8fe3
user:        ohair
date:        Tue May 25 15:58:33 2010 -0700
summary:     6943119: Rebrand source copyright notices

changeset:   248:92ea0ac77d2f
parent:      184:79b594e72df0
user:        emcmanus
date:        Tue Apr 22 18:58:40 2008 +0200
summary:     6692027: Custom subclasses of QueryEval don't serialize

```

**Comment by dougxc** [comment]
Closing this as a test bug.

**Comment by christhalinger** [comment]
Is there a corresponding OpenJDK to fix the test?  I didn't file one.

**Comment by dougxc** [comment]
Can you please file one.

**Comment by christhalinger** [comment]
Your management-delegation skill level is "guru".
